# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
            ],
            options={
                'verbose_name': 'Group Company',
                'verbose_name_plural': 'Group Companies',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='MultiCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='multi_company.groupcompany')),
            ],
            options={
                'verbose_name': 'Multi Company',
                'verbose_name_plural': 'Multi Companies',
                'unique_together': {('parent_company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LocationBasedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('production', 'Production'), ('warehouse', 'Warehouse'), ('office', 'Office'), ('showroom', 'Showroom')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_company_operations', to='core.location')),
                ('multi_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='multi_company.multicompany')),
            ],
            options={
                'verbose_name': 'Location Based Operation',
                'verbose_name_plural': 'Location Based Operations',
            },
        ),
    ]
