"""
Generated API URL configuration.
Includes all schema-defined endpoints routed to generated viewsets.

This file provides an alternative to the individual app URL configs.
To use it, replace the corresponding includes in api/urls.py
with: path("v1/", include("api.generated_urls")),
"""
from django.urls import include, path

app_name = "api"

urlpatterns = [
    path("v1/accessories/", include("api.generated.inventory.urls")),
    path("v1/accounts-payable/", include("api.generated.accounts.urls")),
    path("v1/accounts-receivable/", include("api.generated.accounts.urls")),
    path("v1/ai/chat/", include("api.generated.ai.urls")),
    path("v1/ai/conversations/", include("api.generated.ai.urls")),
    path("v1/alarm-notifications/", include("api.generated.tna.urls")),
    path("v1/asset-categories/", include("api.generated.fixed_assets.urls")),
    path("v1/attendance/", include("api.generated.hr.urls")),
    path("v1/auth/", include("api.generated.authentication.urls")),
    path("v1/bills-of-exchange/", include("api.generated.commercial.urls")),
    path("v1/bonuses/", include("api.generated.hr.urls")),
    path("v1/buyer-communications/", include("api.generated.crm.urls")),
    path("v1/buyer-enquiries/", include("api.generated.merchandising.urls")),
    path("v1/buyer-portfolios/", include("api.generated.buyers.urls")),
    path("v1/buyer-profitabilities/", include("api.generated.crm.urls")),
    path("v1/buyer-ratings/", include("api.generated.buyers.urls")),
    path("v1/buyers/", include("api.generated.buyers.urls")),
    path("v1/capacity-bookings/", include("api.generated.scheduling.urls")),
    path("v1/chart-of-accounts/", include("api.generated.accounts.urls")),
    path("v1/companies/", include("api.generated.multi_company.urls")),
    path("v1/compliance-records/", include("api.generated.compliance.urls")),
    path("v1/cost-centers/", include("api.generated.accounts.urls")),
    path("v1/cost-sheets/", include("api.generated.costing.urls")),
    path("v1/cutting-records/", include("api.generated.production.urls")),
    path("v1/dashboards/", include("api.generated.reporting.urls")),
    path("v1/defect-categories/", include("api.generated.quality.urls")),
    path("v1/departments/", include("api.generated.hr.urls")),
    path("v1/depreciation-schedules/", include("api.generated.fixed_assets.urls")),
    path("v1/designations/", include("api.generated.hr.urls")),
    path("v1/development-monitoring/", include("api.generated.merchandising.urls")),
    path("v1/employees/", include("api.generated.hr.urls")),
    path("v1/endline-qc/", include("api.generated.quality.urls")),
    path("v1/expenses/", include("api.generated.accounts.urls")),
    path("v1/fabric-inspections/", include("api.generated.quality.urls")),
    path("v1/fabrics/", include("api.generated.inventory.urls")),
    path("v1/final-inspections/", include("api.generated.quality.urls")),
    path("v1/fixed-assets/", include("api.generated.fixed_assets.urls")),
    path("v1/floor-requisitions/", include("api.generated.production.urls")),
    path("v1/group-companies/", include("api.generated.multi_company.urls")),
    path("v1/inline-qc/", include("api.generated.quality.urls")),
    path("v1/inspection-packing/", include("api.generated.production.urls")),
    path("v1/invoices/", include("api.generated.accounts.urls")),
    path("v1/job-orders/", include("api.generated.orders.urls")),
    path("v1/journal-entries/", include("api.generated.accounts.urls")),
    path("v1/lcs/", include("api.generated.commercial.urls")),
    path("v1/leaves/", include("api.generated.hr.urls")),
    path("v1/line-plans/", include("api.generated.scheduling.urls")),
    path("v1/location-operations/", include("api.generated.multi_company.urls")),
    path("v1/order-amendment-histories/", include("api.generated.crm.urls")),
    path("v1/orders/", include("api.generated.orders.urls")),
    path("v1/overtime/", include("api.generated.hr.urls")),
    path("v1/performance-records/", include("api.generated.performance.urls")),
    path("v1/physical-inventories/", include("api.generated.inventory.urls")),
    path("v1/plans/", include("api.generated.planning.urls")),
    path("v1/pre-costings/", include("api.generated.costing.urls")),
    path("v1/production-lines/", include("api.generated.production.urls")),
    path("v1/production-orders/", include("api.generated.production.urls")),
    path("v1/production-plans/", include("api.generated.scheduling.urls")),
    path("v1/purchase-orders/", include("api.generated.procurement.urls")),
    path("v1/quotation-analyses/", include("api.generated.procurement.urls")),
    path("v1/rejection-reports/", include("api.generated.quality.urls")),
    path("v1/reports/", include("api.generated.reporting.urls")),
    path("v1/risk-assessments/", include("api.generated.compliance.urls")),
    path("v1/rm-bookings/", include("api.generated.procurement.urls")),
    path("v1/rm-requisitions/", include("api.generated.procurement.urls")),
    path("v1/salary-sheets/", include("api.generated.hr.urls")),
    path("v1/sample-orders/", include("api.generated.orders.urls")),
    path("v1/stock-movements/", include("api.generated.inventory.urls")),
    path("v1/styles/", include("api.generated.merchandising.urls")),
    path("v1/subcontract-orders/", include("api.generated.subcontract.urls")),
    path("v1/subcontract-tracking/", include("api.generated.subcontract.urls")),
    path("v1/suppliers/", include("api.generated.procurement.urls")),
    path("v1/trims/", include("api.generated.inventory.urls")),
    path("v1/warehouses/", include("api.generated.inventory.urls")),
]
