import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getAlarmNotifications = (params?: Record<string, unknown>) => gqlList("tna", "AlarmNotification", params)
export const getAlarmNotification = (id: number) => gqlGet("tna", "AlarmNotification", id)
export const getChartOfAccounts = (params?: Record<string, unknown>) => gqlList("accounts", "ChartOfAccount", params)
export const getChartOfAccount = (id: number) => gqlGet("accounts", "ChartOfAccount", id)
export const createChartOfAccount = (data: Record<string, unknown>) => gqlCreate("accounts", "ChartOfAccount", data)
export const updateChartOfAccount = (id: number, data: Record<string, unknown>) => gqlUpdate("accounts", "ChartOfAccount", id, data)
export const patchChartOfAccount = (id: number, data: Record<string, unknown>) => gqlUpdate("accounts", "ChartOfAccount", id, data)
export const deleteChartOfAccount = (id: number) => gqlDelete("accounts", "ChartOfAccount", id)
export const getCompanies = (params?: Record<string, unknown>) => gqlList("multi_company", "MultiCompany", params)
export const getCompany = (id: number) => gqlGet("multi_company", "MultiCompany", id)
export const createCompany = (data: Record<string, unknown>) => gqlCreate("multi_company", "MultiCompany", data)
export const updateCompany = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "MultiCompany", id, data)
export const patchCompany = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "MultiCompany", id, data)
export const deleteCompany = (id: number) => gqlDelete("multi_company", "MultiCompany", id)
export const getCostCenters = (params?: Record<string, unknown>) => gqlList("accounts", "CostCenter", params)
export const getCostCenter = (id: number) => gqlGet("accounts", "CostCenter", id)
export const createCostCenter = (data: Record<string, unknown>) => gqlCreate("accounts", "CostCenter", data)
export const updateCostCenter = (id: number, data: Record<string, unknown>) => gqlUpdate("accounts", "CostCenter", id, data)
export const patchCostCenter = (id: number, data: Record<string, unknown>) => gqlUpdate("accounts", "CostCenter", id, data)
export const deleteCostCenter = (id: number) => gqlDelete("accounts", "CostCenter", id)
export const getGroupCompanies = (params?: Record<string, unknown>) => gqlList("multi_company", "GroupCompany", params)
export const getGroupCompany = (id: number) => gqlGet("multi_company", "GroupCompany", id)
export const createGroupCompany = (data: Record<string, unknown>) => gqlCreate("multi_company", "GroupCompany", data)
export const updateGroupCompany = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "GroupCompany", id, data)
export const patchGroupCompany = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "GroupCompany", id, data)
export const deleteGroupCompany = (id: number) => gqlDelete("multi_company", "GroupCompany", id)
export const getLocationOperations = (params?: Record<string, unknown>) => gqlList("multi_company", "LocationBasedOperation", params)
export const getLocationOperation = (id: number) => gqlGet("multi_company", "LocationBasedOperation", id)
export const createLocationOperation = (data: Record<string, unknown>) => gqlCreate("multi_company", "LocationBasedOperation", data)
export const updateLocationOperation = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "LocationBasedOperation", id, data)
export const patchLocationOperation = (id: number, data: Record<string, unknown>) => gqlUpdate("multi_company", "LocationBasedOperation", id, data)
export const deleteLocationOperation = (id: number) => gqlDelete("multi_company", "LocationBasedOperation", id)
