import { restList, restGet, restCreate, restUpdate, restDelete } from "./rest"

export const getAlarmNotifications = (params?: Record<string, unknown>) => restList("tna", "AlarmNotification", params)
export const getAlarmNotification = (id: number) => restGet("tna", "AlarmNotification", id)
export const getChartOfAccounts = (params?: Record<string, unknown>) => restList("accounts", "ChartOfAccount", params)
export const getChartOfAccount = (id: number) => restGet("accounts", "ChartOfAccount", id)
export const createChartOfAccount = (data: Record<string, unknown>) => restCreate("accounts", "ChartOfAccount", data)
export const updateChartOfAccount = (id: number, data: Record<string, unknown>) => restUpdate("accounts", "ChartOfAccount", id, data)
export const patchChartOfAccount = (id: number, data: Record<string, unknown>) => restUpdate("accounts", "ChartOfAccount", id, data)
export const deleteChartOfAccount = (id: number) => restDelete("accounts", "ChartOfAccount", id)
export const getCompanies = (params?: Record<string, unknown>) => restList("multi_company", "MultiCompany", params)
export const getCompany = (id: number) => restGet("multi_company", "MultiCompany", id)
export const createCompany = (data: Record<string, unknown>) => restCreate("multi_company", "MultiCompany", data)
export const updateCompany = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "MultiCompany", id, data)
export const patchCompany = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "MultiCompany", id, data)
export const deleteCompany = (id: number) => restDelete("multi_company", "MultiCompany", id)
export const getCostCenters = (params?: Record<string, unknown>) => restList("accounts", "CostCenter", params)
export const getCostCenter = (id: number) => restGet("accounts", "CostCenter", id)
export const createCostCenter = (data: Record<string, unknown>) => restCreate("accounts", "CostCenter", data)
export const updateCostCenter = (id: number, data: Record<string, unknown>) => restUpdate("accounts", "CostCenter", id, data)
export const patchCostCenter = (id: number, data: Record<string, unknown>) => restUpdate("accounts", "CostCenter", id, data)
export const deleteCostCenter = (id: number) => restDelete("accounts", "CostCenter", id)
export const getGroupCompanies = (params?: Record<string, unknown>) => restList("multi_company", "GroupCompany", params)
export const getGroupCompany = (id: number) => restGet("multi_company", "GroupCompany", id)
export const createGroupCompany = (data: Record<string, unknown>) => restCreate("multi_company", "GroupCompany", data)
export const updateGroupCompany = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "GroupCompany", id, data)
export const patchGroupCompany = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "GroupCompany", id, data)
export const deleteGroupCompany = (id: number) => restDelete("multi_company", "GroupCompany", id)
export const getLocationOperations = (params?: Record<string, unknown>) => restList("multi_company", "LocationBasedOperation", params)
export const getLocationOperation = (id: number) => restGet("multi_company", "LocationBasedOperation", id)
export const createLocationOperation = (data: Record<string, unknown>) => restCreate("multi_company", "LocationBasedOperation", data)
export const updateLocationOperation = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "LocationBasedOperation", id, data)
export const patchLocationOperation = (id: number, data: Record<string, unknown>) => restUpdate("multi_company", "LocationBasedOperation", id, data)
export const deleteLocationOperation = (id: number) => restDelete("multi_company", "LocationBasedOperation", id)
