import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getBuyers = (params?: Record<string, unknown>) => gqlList("buyers", "Buyer", params)
export const getBuyer = (id: number) => gqlGet("buyers", "Buyer", id)
export const createBuyer = (data: Record<string, unknown>) => gqlCreate("buyers", "Buyer", data)
export const updateBuyer = (id: number, data: Record<string, unknown>) => gqlUpdate("buyers", "Buyer", id, data)
export const patchBuyer = (id: number, data: Record<string, unknown>) => gqlUpdate("buyers", "Buyer", id, data)
export const deleteBuyer = (id: number) => gqlDelete("buyers", "Buyer", id)
export const getBuyerCommunications = (params?: Record<string, unknown>) => gqlList("crm", "BuyerCommunication", params)
export const getBuyerCommunication = (id: number) => gqlGet("crm", "BuyerCommunication", id)
export const createBuyerCommunication = (data: Record<string, unknown>) => gqlCreate("crm", "BuyerCommunication", data)
export const getBuyerPortfolios = (params?: Record<string, unknown>) => gqlList("buyers", "BuyerPortfolio", params)
export const getBuyerPortfolio = (id: number) => gqlGet("buyers", "BuyerPortfolio", id)
export const getOrderAmendments = (params?: Record<string, unknown>) => gqlList("crm", "OrderAmendmentHistory", params)
export const getOrderAmendment = (id: number) => gqlGet("crm", "OrderAmendmentHistory", id)
export const getBuyerProfitabilities = (params?: Record<string, unknown>) => gqlList("crm", "BuyerProfitability", params)
export const getBuyerProfitability = (id: number) => gqlGet("crm", "BuyerProfitability", id)
export const getBuyerRatings = (params?: Record<string, unknown>) => gqlList("buyers", "BuyerRating", params)
export const getBuyerRating = (id: number) => gqlGet("buyers", "BuyerRating", id)
