import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getAttendance = (params?: Record<string, unknown>) => gqlList("hr", "Attendance", params)
export const getAttendanceRecord = (id: number) => gqlGet("hr", "Attendance", id)
export const createAttendance = (data: Record<string, unknown>) => gqlCreate("hr", "Attendance", data)
export const updateAttendance = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Attendance", id, data)
export const patchAttendance = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Attendance", id, data)
export const deleteAttendance = (id: number) => gqlDelete("hr", "Attendance", id)
export const getBonuses = (params?: Record<string, unknown>) => gqlList("hr", "Bonus", params)
export const getBonus = (id: number) => gqlGet("hr", "Bonus", id)
export const createBonus = (data: Record<string, unknown>) => gqlCreate("hr", "Bonus", data)
export const updateBonus = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Bonus", id, data)
export const patchBonus = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Bonus", id, data)
export const deleteBonus = (id: number) => gqlDelete("hr", "Bonus", id)
export const getDepartments = (params?: Record<string, unknown>) => gqlList("hr", "Department", params)
export const getDepartment = (id: number) => gqlGet("hr", "Department", id)
export const createDepartment = (data: Record<string, unknown>) => gqlCreate("hr", "Department", data)
export const updateDepartment = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Department", id, data)
export const patchDepartment = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Department", id, data)
export const deleteDepartment = (id: number) => gqlDelete("hr", "Department", id)
export const getDesignations = (params?: Record<string, unknown>) => gqlList("hr", "Designation", params)
export const getDesignation = (id: number) => gqlGet("hr", "Designation", id)
export const createDesignation = (data: Record<string, unknown>) => gqlCreate("hr", "Designation", data)
export const updateDesignation = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Designation", id, data)
export const patchDesignation = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Designation", id, data)
export const deleteDesignation = (id: number) => gqlDelete("hr", "Designation", id)
export const getEmployees = (params?: Record<string, unknown>) => gqlList("hr", "Employee", params)
export const getEmployee = (id: number) => gqlGet("hr", "Employee", id)
export const createEmployee = (data: Record<string, unknown>) => gqlCreate("hr", "Employee", data)
export const updateEmployee = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Employee", id, data)
export const patchEmployee = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Employee", id, data)
export const deleteEmployee = (id: number) => gqlDelete("hr", "Employee", id)
export const getLeaves = (params?: Record<string, unknown>) => gqlList("hr", "Leave", params)
export const getLeave = (id: number) => gqlGet("hr", "Leave", id)
export const createLeave = (data: Record<string, unknown>) => gqlCreate("hr", "Leave", data)
export const updateLeave = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Leave", id, data)
export const patchLeave = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Leave", id, data)
export const deleteLeave = (id: number) => gqlDelete("hr", "Leave", id)
export const getOvertime = (params?: Record<string, unknown>) => gqlList("hr", "Overtime", params)
export const getOvertimeRecord = (id: number) => gqlGet("hr", "Overtime", id)
export const createOvertime = (data: Record<string, unknown>) => gqlCreate("hr", "Overtime", data)
export const updateOvertime = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Overtime", id, data)
export const patchOvertime = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "Overtime", id, data)
export const deleteOvertime = (id: number) => gqlDelete("hr", "Overtime", id)
export const getPerformanceRecords = (params?: Record<string, unknown>) => gqlList("performance", "PerformanceRecord", params)
export const getPerformanceRecord = (id: number) => gqlGet("performance", "PerformanceRecord", id)
export const createPerformanceRecord = (data: Record<string, unknown>) => gqlCreate("performance", "PerformanceRecord", data)
export const updatePerformanceRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("performance", "PerformanceRecord", id, data)
export const patchPerformanceRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("performance", "PerformanceRecord", id, data)
export const deletePerformanceRecord = (id: number) => gqlDelete("performance", "PerformanceRecord", id)
export const getSalarySheets = (params?: Record<string, unknown>) => gqlList("hr", "SalarySheet", params)
export const getSalarySheet = (id: number) => gqlGet("hr", "SalarySheet", id)
export const createSalarySheet = (data: Record<string, unknown>) => gqlCreate("hr", "SalarySheet", data)
export const updateSalarySheet = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "SalarySheet", id, data)
export const patchSalarySheet = (id: number, data: Record<string, unknown>) => gqlUpdate("hr", "SalarySheet", id, data)
export const deleteSalarySheet = (id: number) => gqlDelete("hr", "SalarySheet", id)
