import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getAccessories = (params?: Record<string, unknown>) => gqlList("inventory", "Accessory", params)
export const getAccessory = (id: number) => gqlGet("inventory", "Accessory", id)
export const createAccessory = (data: Record<string, unknown>) => gqlCreate("inventory", "Accessory", data)
export const updateAccessory = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Accessory", id, data)
export const patchAccessory = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Accessory", id, data)
export const deleteAccessory = (id: number) => gqlDelete("inventory", "Accessory", id)
export const getFabrics = (params?: Record<string, unknown>) => gqlList("inventory", "Fabric", params)
export const getFabric = (id: number) => gqlGet("inventory", "Fabric", id)
export const createFabric = (data: Record<string, unknown>) => gqlCreate("inventory", "Fabric", data)
export const updateFabric = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Fabric", id, data)
export const patchFabric = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Fabric", id, data)
export const deleteFabric = (id: number) => gqlDelete("inventory", "Fabric", id)
export const getFabricInspections = (params?: Record<string, unknown>) => gqlList("quality", "FabricInspection", params)
export const getFabricInspection = (id: number) => gqlGet("quality", "FabricInspection", id)
export const createFabricInspection = (data: Record<string, unknown>) => gqlCreate("quality", "FabricInspection", data)
export const updateFabricInspection = (id: number, data: Record<string, unknown>) => gqlUpdate("quality", "FabricInspection", id, data)
export const patchFabricInspection = (id: number, data: Record<string, unknown>) => gqlUpdate("quality", "FabricInspection", id, data)
export const deleteFabricInspection = (id: number) => gqlDelete("quality", "FabricInspection", id)
export const getFloorRequisitions = (params?: Record<string, unknown>) => gqlList("production", "FloorRequisition", params)
export const getFloorRequisition = (id: number) => gqlGet("production", "FloorRequisition", id)
export const createFloorRequisition = (data: Record<string, unknown>) => gqlCreate("production", "FloorRequisition", data)
export const updateFloorRequisition = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "FloorRequisition", id, data)
export const patchFloorRequisition = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "FloorRequisition", id, data)
export const deleteFloorRequisition = (id: number) => gqlDelete("production", "FloorRequisition", id)
export const getPhysicalInventories = (params?: Record<string, unknown>) => gqlList("inventory", "PhysicalInventory", params)
export const getPhysicalInventory = (id: number) => gqlGet("inventory", "PhysicalInventory", id)
export const createPhysicalInventory = (data: Record<string, unknown>) => gqlCreate("inventory", "PhysicalInventory", data)
export const updatePhysicalInventory = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "PhysicalInventory", id, data)
export const patchPhysicalInventory = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "PhysicalInventory", id, data)
export const deletePhysicalInventory = (id: number) => gqlDelete("inventory", "PhysicalInventory", id)
export const getRmBookings = (params?: Record<string, unknown>) => gqlList("procurement", "RawMaterialBooking", params)
export const getRmBooking = (id: number) => gqlGet("procurement", "RawMaterialBooking", id)
export const createRmBooking = (data: Record<string, unknown>) => gqlCreate("procurement", "RawMaterialBooking", data)
export const updateRmBooking = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "RawMaterialBooking", id, data)
export const patchRmBooking = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "RawMaterialBooking", id, data)
export const deleteRmBooking = (id: number) => gqlDelete("procurement", "RawMaterialBooking", id)
export const getRmRequisitions = (params?: Record<string, unknown>) => gqlList("procurement", "RawMaterialRequisition", params)
export const getRmRequisition = (id: number) => gqlGet("procurement", "RawMaterialRequisition", id)
export const createRmRequisition = (data: Record<string, unknown>) => gqlCreate("procurement", "RawMaterialRequisition", data)
export const updateRmRequisition = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "RawMaterialRequisition", id, data)
export const patchRmRequisition = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "RawMaterialRequisition", id, data)
export const deleteRmRequisition = (id: number) => gqlDelete("procurement", "RawMaterialRequisition", id)
export const getStockMovements = (params?: Record<string, unknown>) => gqlList("inventory", "StockMovement", params)
export const getStockMovement = (id: number) => gqlGet("inventory", "StockMovement", id)
export const createStockMovement = (data: Record<string, unknown>) => gqlCreate("inventory", "StockMovement", data)
export const updateStockMovement = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "StockMovement", id, data)
export const patchStockMovement = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "StockMovement", id, data)
export const deleteStockMovement = (id: number) => gqlDelete("inventory", "StockMovement", id)
export const getTrims = (params?: Record<string, unknown>) => gqlList("inventory", "Trim", params)
export const getTrim = (id: number) => gqlGet("inventory", "Trim", id)
export const createTrim = (data: Record<string, unknown>) => gqlCreate("inventory", "Trim", data)
export const updateTrim = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Trim", id, data)
export const patchTrim = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Trim", id, data)
export const deleteTrim = (id: number) => gqlDelete("inventory", "Trim", id)
export const getWarehouses = (params?: Record<string, unknown>) => gqlList("inventory", "Warehouse", params)
export const getWarehouse = (id: number) => gqlGet("inventory", "Warehouse", id)
export const createWarehouse = (data: Record<string, unknown>) => gqlCreate("inventory", "Warehouse", data)
export const updateWarehouse = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Warehouse", id, data)
export const patchWarehouse = (id: number, data: Record<string, unknown>) => gqlUpdate("inventory", "Warehouse", id, data)
export const deleteWarehouse = (id: number) => gqlDelete("inventory", "Warehouse", id)
