import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getOrders = (params?: Record<string, unknown>) => gqlList("orders", "Order", params)
export const getOrder = (id: number) => gqlGet("orders", "Order", id)
export const createOrder = (data: Record<string, unknown>) => gqlCreate("orders", "Order", data)
export const updateOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("orders", "Order", id, data)
export const patchOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("orders", "Order", id, data)
export const deleteOrder = (id: number) => gqlDelete("orders", "Order", id)
export const getOrderAmendments = (params?: Record<string, unknown>) => gqlList("crm", "OrderAmendmentHistory", params)
export const getOrderAmendment = (id: number) => gqlGet("crm", "OrderAmendmentHistory", id)
export const createOrderAmendment = (data: Record<string, unknown>) => gqlCreate("crm", "OrderAmendmentHistory", data)
export const updateOrderAmendment = (id: number, data: Record<string, unknown>) => gqlUpdate("crm", "OrderAmendmentHistory", id, data)
export const patchOrderAmendment = (id: number, data: Record<string, unknown>) => gqlUpdate("crm", "OrderAmendmentHistory", id, data)
export const deleteOrderAmendment = (id: number) => gqlDelete("crm", "OrderAmendmentHistory", id)
export const getSampleOrders = (params?: Record<string, unknown>) => gqlList("merchandising", "SampleOrder", params)
export const getSampleOrder = (id: number) => gqlGet("merchandising", "SampleOrder", id)
export const createSampleOrder = (data: Record<string, unknown>) => gqlCreate("merchandising", "SampleOrder", data)
export const updateSampleOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "SampleOrder", id, data)
export const patchSampleOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "SampleOrder", id, data)
export const deleteSampleOrder = (id: number) => gqlDelete("merchandising", "SampleOrder", id)
export const getShipments = (params?: Record<string, unknown>) => gqlList("commercial", "Shipment", params)
export const getShipment = (id: number) => gqlGet("commercial", "Shipment", id)
export const createShipment = (data: Record<string, unknown>) => gqlCreate("commercial", "Shipment", data)
export const updateShipment = (id: number, data: Record<string, unknown>) => gqlUpdate("commercial", "Shipment", id, data)
export const patchShipment = (id: number, data: Record<string, unknown>) => gqlUpdate("commercial", "Shipment", id, data)
export const deleteShipment = (id: number) => gqlDelete("commercial", "Shipment", id)
