import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getPurchaseOrders = (params?: Record<string, unknown>) => gqlList("merchandising", "PurchaseOrder", params)
export const getPurchaseOrder = (id: number) => gqlGet("merchandising", "PurchaseOrder", id)
export const createPurchaseOrder = (data: Record<string, unknown>) => gqlCreate("merchandising", "PurchaseOrder", data)
export const updatePurchaseOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "PurchaseOrder", id, data)
export const patchPurchaseOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "PurchaseOrder", id, data)
export const deletePurchaseOrder = (id: number) => gqlDelete("merchandising", "PurchaseOrder", id)
export const getQuotationAnalyses = (params?: Record<string, unknown>) => gqlList("procurement", "QuotationAnalysis", params)
export const getQuotationAnalysis = (id: number) => gqlGet("procurement", "QuotationAnalysis", id)
export const createQuotationAnalysis = (data: Record<string, unknown>) => gqlCreate("procurement", "QuotationAnalysis", data)
export const updateQuotationAnalysis = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "QuotationAnalysis", id, data)
export const patchQuotationAnalysis = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "QuotationAnalysis", id, data)
export const deleteQuotationAnalysis = (id: number) => gqlDelete("procurement", "QuotationAnalysis", id)
export const getSuppliers = (params?: Record<string, unknown>) => gqlList("procurement", "Supplier", params)
export const getSupplier = (id: number) => gqlGet("procurement", "Supplier", id)
export const createSupplier = (data: Record<string, unknown>) => gqlCreate("procurement", "Supplier", data)
export const updateSupplier = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "Supplier", id, data)
export const patchSupplier = (id: number, data: Record<string, unknown>) => gqlUpdate("procurement", "Supplier", id, data)
export const deleteSupplier = (id: number) => gqlDelete("procurement", "Supplier", id)
