import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getCapacityBookings = (params?: Record<string, unknown>) => gqlList("ie_planning", "CapacityBooking", params)
export const getCapacityBooking = (id: number) => gqlGet("ie_planning", "CapacityBooking", id)
export const createCapacityBooking = (data: Record<string, unknown>) => gqlCreate("ie_planning", "CapacityBooking", data)
export const updateCapacityBooking = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "CapacityBooking", id, data)
export const patchCapacityBooking = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "CapacityBooking", id, data)
export const deleteCapacityBooking = (id: number) => gqlDelete("ie_planning", "CapacityBooking", id)
export const getCuttingRecords = (params?: Record<string, unknown>) => gqlList("production", "CuttingRecord", params)
export const getCuttingRecord = (id: number) => gqlGet("production", "CuttingRecord", id)
export const createCuttingRecord = (data: Record<string, unknown>) => gqlCreate("production", "CuttingRecord", data)
export const updateCuttingRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "CuttingRecord", id, data)
export const patchCuttingRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "CuttingRecord", id, data)
export const deleteCuttingRecord = (id: number) => gqlDelete("production", "CuttingRecord", id)
export const getJobOrders = (params?: Record<string, unknown>) => gqlList("tna", "JobOrder", params)
export const getJobOrder = (id: number) => gqlGet("tna", "JobOrder", id)
export const createJobOrder = (data: Record<string, unknown>) => gqlCreate("tna", "JobOrder", data)
export const updateJobOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "JobOrder", id, data)
export const patchJobOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "JobOrder", id, data)
export const deleteJobOrder = (id: number) => gqlDelete("tna", "JobOrder", id)
export const getLinePlans = (params?: Record<string, unknown>) => gqlList("ie_planning", "LinePlan", params)
export const getLinePlan = (id: number) => gqlGet("ie_planning", "LinePlan", id)
export const createLinePlan = (data: Record<string, unknown>) => gqlCreate("ie_planning", "LinePlan", data)
export const updateLinePlan = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "LinePlan", id, data)
export const patchLinePlan = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "LinePlan", id, data)
export const deleteLinePlan = (id: number) => gqlDelete("ie_planning", "LinePlan", id)
export const getProductionLines = (params?: Record<string, unknown>) => gqlList("production", "ProductionLine", params)
export const getProductionLine = (id: number) => gqlGet("production", "ProductionLine", id)
export const createProductionLine = (data: Record<string, unknown>) => gqlCreate("production", "ProductionLine", data)
export const updateProductionLine = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "ProductionLine", id, data)
export const patchProductionLine = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "ProductionLine", id, data)
export const deleteProductionLine = (id: number) => gqlDelete("production", "ProductionLine", id)
export const getProductionOrders = (params?: Record<string, unknown>) => gqlList("production", "ProductionOrder", params)
export const getProductionOrder = (id: number) => gqlGet("production", "ProductionOrder", id)
export const createProductionOrder = (data: Record<string, unknown>) => gqlCreate("production", "ProductionOrder", data)
export const updateProductionOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "ProductionOrder", id, data)
export const patchProductionOrder = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "ProductionOrder", id, data)
export const deleteProductionOrder = (id: number) => gqlDelete("production", "ProductionOrder", id)
export const getProductionPlans = (params?: Record<string, unknown>) => gqlList("ie_planning", "ProductionPlan", params)
export const getProductionPlan = (id: number) => gqlGet("ie_planning", "ProductionPlan", id)
export const createProductionPlan = (data: Record<string, unknown>) => gqlCreate("ie_planning", "ProductionPlan", data)
export const updateProductionPlan = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "ProductionPlan", id, data)
export const patchProductionPlan = (id: number, data: Record<string, unknown>) => gqlUpdate("ie_planning", "ProductionPlan", id, data)
export const deleteProductionPlan = (id: number) => gqlDelete("ie_planning", "ProductionPlan", id)
export const getSewingRecords = (params?: Record<string, unknown>) => gqlList("production", "SewingRecord", params)
export const getSewingRecord = (id: number) => gqlGet("production", "SewingRecord", id)
export const createSewingRecord = (data: Record<string, unknown>) => gqlCreate("production", "SewingRecord", data)
export const updateSewingRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "SewingRecord", id, data)
export const patchSewingRecord = (id: number, data: Record<string, unknown>) => gqlUpdate("production", "SewingRecord", id, data)
export const deleteSewingRecord = (id: number) => gqlDelete("production", "SewingRecord", id)
export const getDevelopmentMonitoring = (params?: Record<string, unknown>) => gqlList("merchandising", "DevelopmentMonitoring", params)
export const getDevelopmentMonitor = (id: number) => gqlGet("merchandising", "DevelopmentMonitoring", id)
export const createDevelopmentMonitor = (data: Record<string, unknown>) => gqlCreate("merchandising", "DevelopmentMonitoring", data)
export const updateDevelopmentMonitor = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "DevelopmentMonitoring", id, data)
export const patchDevelopmentMonitor = (id: number, data: Record<string, unknown>) => gqlUpdate("merchandising", "DevelopmentMonitoring", id, data)
export const deleteDevelopmentMonitor = (id: number) => gqlDelete("merchandising", "DevelopmentMonitoring", id)
export const getPlans = (params?: Record<string, unknown>) => gqlList("planning", "Plan", params)
export const getPlan = (id: number) => gqlGet("planning", "Plan", id)
export const createPlan = (data: Record<string, unknown>) => gqlCreate("planning", "Plan", data)
export const updatePlan = (id: number, data: Record<string, unknown>) => gqlUpdate("planning", "Plan", id, data)
export const patchPlan = (id: number, data: Record<string, unknown>) => gqlUpdate("planning", "Plan", id, data)
export const deletePlan = (id: number) => gqlDelete("planning", "Plan", id)
