import { gqlList, gqlGet, gqlCreate, gqlUpdate, gqlDelete } from "./graphql"

export const getSchedules = (params?: Record<string, unknown>) => gqlList("scheduling", "Schedule", params)
export const getSchedule = (id: number) => gqlGet("scheduling", "Schedule", id)
export const createSchedule = (data: Record<string, unknown>) => gqlCreate("scheduling", "Schedule", data)
export const updateSchedule = (id: number, data: Record<string, unknown>) => gqlUpdate("scheduling", "Schedule", id, data)
export const patchSchedule = (id: number, data: Record<string, unknown>) => gqlUpdate("scheduling", "Schedule", id, data)
export const deleteSchedule = (id: number) => gqlDelete("scheduling", "Schedule", id)
export const getTasks = (params?: Record<string, unknown>) => gqlList("tna", "Task", params)
export const getTask = (id: number) => gqlGet("tna", "Task", id)
export const createTask = (data: Record<string, unknown>) => gqlCreate("tna", "Task", data)
export const updateTask = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "Task", id, data)
export const patchTask = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "Task", id, data)
export const deleteTask = (id: number) => gqlDelete("tna", "Task", id)
export const getTimelines = (params?: Record<string, unknown>) => gqlList("tna", "Timeline", params)
export const getTimeline = (id: number) => gqlGet("tna", "Timeline", id)
export const createTimeline = (data: Record<string, unknown>) => gqlCreate("tna", "Timeline", data)
export const updateTimeline = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "Timeline", id, data)
export const patchTimeline = (id: number, data: Record<string, unknown>) => gqlUpdate("tna", "Timeline", id, data)
export const deleteTimeline = (id: number) => gqlDelete("tna", "Timeline", id)
