# Generated by Django 6.0.6 on 2026-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        ('users', '0003_organization_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_machines', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('target_qty', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_orders', to='users.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_orders', to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('cutting_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cutting.cuttingmachine')),
                ('cutting_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='cutting.cuttingorder')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width_inches', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length_yards', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cutting_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='cutting.cuttingorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NestingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nesting_plan', to='cutting.marker')),
            ],
        ),
        migrations.CreateModel(
            name='NestingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waste_area_sq_yards', models.DecimalField(decimal_places=2, max_digits=6)),
                ('piece_count', models.PositiveIntegerField()),
                ('nesting_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='cutting.nestingplan')),
            ],
        ),
        migrations.CreateModel(
            name='PatternPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=100)),
                ('geometry', models.JSONField()),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='cutting.marker')),
            ],
        ),
    ]
