# Generated by Django 6.0.6 on 2026-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_organization_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OEELog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oee_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oee_logs', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='LineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_capacity_pcs', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('checked_units', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_logs', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='BottleneckAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottleneck_alerts', to='production.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_pcs', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='production.productionline')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='production.productionshift')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_units', to='users.organization')),
            ],
        ),
        migrations.AddField(
            model_name='productionline',
            name='production_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productionunit'),
        ),
    ]
