# Generated by Django 6.0.7 on 2026-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('core', '0001_initial'),
        ('merchandising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('dishonored', 'Dishonored')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_exchange', to='buyers.buyer')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_exchange', to='core.organization')),
            ],
            options={
                'verbose_name': 'Bill of Exchange',
                'verbose_name_plural': 'Bills of Exchange',
                'unique_together': {('organization', 'bill_number')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_invoices', to='buyers.buyer')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_invoices', to='core.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_invoices', to='merchandising.purchaseorder')),
            ],
            options={
                'verbose_name': 'Commercial Invoice',
                'verbose_name_plural': 'Commercial Invoices',
                'unique_together': {('organization', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('lc_type', models.CharField(choices=[('export', 'Export LC'), ('import', 'Import LC'), ('btb', 'BTB LC')], max_length=50)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issuing_bank', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('amended', 'Amended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcs', to='buyers.buyer')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lcs', to='core.organization')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lcs', to='merchandising.purchaseorder')),
            ],
            options={
                'verbose_name': 'LC',
                'verbose_name_plural': 'LCs',
                'unique_together': {('organization', 'lc_number')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=100)),
                ('shipment_date', models.DateField()),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('port_of_loading', models.CharField(max_length=255)),
                ('port_of_discharge', models.CharField(max_length=255)),
                ('forwarder', models.CharField(blank=True, max_length=255)),
                ('container_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('loaded', 'Loaded'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('arrived', 'Arrived'), ('delivered', 'Delivered')], default='booked', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='buyers.buyer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='merchandising.purchaseorder')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'unique_together': {('organization', 'shipment_number')},
            },
        ),
    ]
