# Generated by Django 6.0.6 on 2026-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        ('production', '0001_initial'),
        ('users', '0003_organization_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_schedules', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='production.productionline')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='orders.purchaseorder')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planning.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='planning.productionplan')),
            ],
        ),
    ]
