# Generated by Django 6.0.6 on 2026-06-23 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_organization_customuser_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_name', models.CharField(max_length=255)),
                ('auditor', models.CharField(max_length=255)),
                ('audit_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='audit_reports/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_description', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('remediation_plan', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='compliance.audit')),
            ],
        ),
        migrations.CreateModel(
            name='CertifyingAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifying_authorities', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document', models.FileField(upload_to='compliance_documents/')),
                ('is_valid', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.certifyingauthority')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('environmental_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('safety_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_scores', to='users.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ESGMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_footprint_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_recycled_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('renewable_energy_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_metrics', to='users.organization')),
            ],
        ),
    ]
